//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cinema_ShowTimesEntities : DbContext
    {
        public Cinema_ShowTimesEntities()
            : base("name=Cinema_ShowTimesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Cinema> tbl_Cinema { get; set; }
        public virtual DbSet<tbl_CinemaScreen> tbl_CinemaScreen { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_Movies> tbl_Movies { get; set; }
        public virtual DbSet<tbl_ShowTime> tbl_ShowTime { get; set; }
    }
}
