//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movies
    {
        public tbl_Movies()
        {
            this.tbl_ShowTime = new HashSet<tbl_ShowTime>();
        }
    
        public int Movies_Id { get; set; }
        public string Movies_Name { get; set; }
        public string Movies_Details { get; set; }
        public string Movies_TrailerURL { get; set; }
        public string Movies_CoverPicture { get; set; }
        public string Movies_Director { get; set; }
        public Nullable<bool> Movies_isDeleted { get; set; }
        public Nullable<System.DateTime> Movies_CreatedDateTime { get; set; }
    
        public virtual ICollection<tbl_ShowTime> tbl_ShowTime { get; set; }
    }
}
