//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int Contact__Id { get; set; }
        public Nullable<int> Contact_Cinema_Id { get; set; }
        public string Contact_Type { get; set; }
        public string Contact_Number { get; set; }
        public Nullable<bool> Contact_isDeleted { get; set; }
        public Nullable<System.DateTime> Contact_CreatedDateTime { get; set; }
    
        public virtual tbl_Cinema tbl_Cinema { get; set; }
    }
}
