//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ShowTime
    {
        public int ShowTime_Id { get; set; }
        public Nullable<int> ShowTime_Cinema_Id { get; set; }
        public Nullable<int> ShowTime_CinemaScreen_Id { get; set; }
        public Nullable<int> ShowTime_Movie_Id { get; set; }
        public Nullable<System.DateTime> ShowTime_Time { get; set; }
        public Nullable<System.DateTime> ShowTime_Date { get; set; }
        public string ShowTime_UserDate { get; set; }
        public Nullable<bool> ShowTime_IsValid { get; set; }
        public Nullable<bool> ShowTime_isDeleted { get; set; }
        public Nullable<System.DateTime> ShowTime_Created_DateTime { get; set; }
    
        public virtual tbl_Cinema tbl_Cinema { get; set; }
        public virtual tbl_CinemaScreen tbl_CinemaScreen { get; set; }
        public virtual tbl_Movies tbl_Movies { get; set; }
    }
}
