//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cinema
    {
        public tbl_Cinema()
        {
            this.tbl_CinemaScreen = new HashSet<tbl_CinemaScreen>();
            this.tbl_Contact = new HashSet<tbl_Contact>();
            this.tbl_ShowTime = new HashSet<tbl_ShowTime>();
        }
    
        public int Cinema_Id { get; set; }
        public string Cinema_Name { get; set; }
        public Nullable<int> Cinema_City_Id { get; set; }
        public string Cinema_Coordinates { get; set; }
        public Nullable<bool> Cinema_isDeleted { get; set; }
        public Nullable<System.DateTime> Cinema_CreatedDateTime { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
        public virtual ICollection<tbl_CinemaScreen> tbl_CinemaScreen { get; set; }
        public virtual ICollection<tbl_Contact> tbl_Contact { get; set; }
        public virtual ICollection<tbl_ShowTime> tbl_ShowTime { get; set; }
    }
}
