//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_City
    {
        public tbl_City()
        {
            this.tbl_Cinema = new HashSet<tbl_Cinema>();
        }
    
        public int City_Id { get; set; }
        public string City_Name { get; set; }
        public Nullable<bool> City_isDeleted { get; set; }
        public Nullable<System.DateTime> City_CreatedDateTime { get; set; }
    
        public virtual ICollection<tbl_Cinema> tbl_Cinema { get; set; }
    }
}
