//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineplexScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CinemaScreen
    {
        public tbl_CinemaScreen()
        {
            this.tbl_ShowTime = new HashSet<tbl_ShowTime>();
        }
    
        public int CinemaScreen_Id { get; set; }
        public string CinemaScreen_Name { get; set; }
        public Nullable<int> CinemaScreen_Cinema_Id { get; set; }
        public Nullable<bool> CinemaScreen_isDeleted { get; set; }
        public Nullable<System.DateTime> CinemaScreen_CreatedDate { get; set; }
    
        public virtual tbl_Cinema tbl_Cinema { get; set; }
        public virtual ICollection<tbl_ShowTime> tbl_ShowTime { get; set; }
    }
}
